In [1]:
import pandas as pd
import numpy as np

In [2]:
master = pd.read_csv(r"C:\Users\Admin\Desktop\IIMSTC\MINI PROJECT\E_Waste_Prediction_Project\master_dataset.csv")
master.head()

,Country,Year,E_Waste,GNI,Internet_Users,Electronics_Imports,GDP_Growth,Urban_Population,Total_Population
0,Brazil,2019,10.200,9410.0,73.9124,35.2,1.2,181356195,206338066
1,Brazil,2020,10.554,8080.0,81.3427,38.4,-3.3,183589871,208814123
2,Brazil,2021,10.921,8060.0,80.6899,45.6,4.8,185850085,211319892
3,Brazil,2022,11.300,8440.0,80.5278,42.1,3.0,188137144,213855731
4,Brazil,2023,11.692,9310.0,84.1506,40.5,2.9,190451360,216422000

In [3]:
correlation =master.corr(numeric_only=True)
correlation

,Year,E_Waste,GNI,Internet_Users,Electronics_Imports,GDP_Growth,Urban_Population,Total_Population
Year,1.000000,0.064229,0.064017,0.305536,0.080051,0.261345,0.010725,-0.029428
E_Waste,0.064229,1.000000,0.885642,0.779489,-0.099226,-0.266141,-0.445979,-0.531521
GNI,0.064017,0.885642,1.000000,0.745167,0.076779,-0.146819,-0.363943,-0.426934
Internet_Users,0.305536,0.779489,0.745167,1.000000,0.093475,-0.064021,-0.328830,-0.492449
Electronics_Imports,0.080051,-0.099226,0.076779,0.093475,1.000000,0.188880,0.788788,0.647538
GDP_Growth,0.261345,-0.266141,-0.146819,-0.064021,0.188880,1.000000,0.194935,0.183638
Urban_Population,0.010725,-0.445979,-0.363943,-0.328830,0.788788,0.194935,1.000000,0.953515
Total_Population,-0.029428,-0.531521,-0.426934,-0.492449,0.647538,0.183638,0.953515,1.000000

In [4]:
correlation["E_Waste"].sort_values(ascending=False)

E_Waste                1.000000
GNI                    0.885642
Internet_Users         0.779489
Year                   0.064229
Electronics_Imports   -0.099226
GDP_Growth            -0.266141
Urban_Population      -0.445979
Total_Population      -0.531521
Name: E_Waste, dtype: float64

In [5]:
features = [
    "GNI",
    "Internet_Users",
    "Electronics_Imports",
    "Urban_Population"
]
x = master[features]
y = master["E_Waste"]