In [1]:
import pandas as pd
import numpy as np

In [2]:
master = pd.read_csv(r"C:\Users\Admin\Desktop\IIMSTC\MINI PROJECT\E_Waste_Prediction_Project\master_dataset.csv")
master.head()

,Country,Year,E_Waste,GNI,Internet_Users,Electronics_Imports,GDP_Growth,Urban_Population,Total_Population
0,Brazil,2019,10.200,9410.0,73.9124,35.2,1.2,181356195,206338066
1,Brazil,2020,10.554,8080.0,81.3427,38.4,-3.3,183589871,208814123
2,Brazil,2021,10.921,8060.0,80.6899,45.6,4.8,185850085,211319892
3,Brazil,2022,11.300,8440.0,80.5278,42.1,3.0,188137144,213855731
4,Brazil,2023,11.692,9310.0,84.1506,40.5,2.9,190451360,216422000

In [3]:
features = [
    "GNI",
    "Internet_Users",
    "Electronics_Imports",
    "Urban_Population"
]
x = master[features]
y = master["E_Waste"]

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X = master[["GNI", "Internet_Users", "Electronics_Imports", "Urban_Population"]]
y = master["E_Waste"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [5]:
r2 = r2_score(y_test, y_pred)

print("R²:", r2)

R²: 0.8754210643150675

In [6]:
coeffefficients=pd.DataFrame({
    "Feature": x.columns,
    "Coefficient": model.coef_
})
coeffefficients.sort_values(by="Coefficient", ascending=False)

               Feature   Coefficient
1       Internet_Users  1.436936e-01
0                  GNI  2.352496e-04
3     Urban_Population  9.180092e-09
2  Electronics_Imports -2.312965e-02

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
model_scaled = LinearRegression()
model_scaled.fit(x_scaled, y)
pd.DataFrame({
    "Feature": x.columns,
    "Standardized_Coefficient": model_scaled.coef_
}).sort_values(by="Standardized_Coefficient", ascending=False)

               Feature  Standardized_Coefficient
0                  GNI                  5.259603
1       Internet_Users                  2.288626
3     Urban_Population                  1.508993
2  Electronics_Imports                 -2.505300

In [8]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd
vif_data = pd.DataFrame()
vif_data["Feature"] = x.columns
vif_data["VIF"] = [variance_inflation_factor(x.values, i) for i in range(x.shape[1])]
vif_data

               Feature       VIF
0                  GNI  7.381902
1       Internet_Users  6.706764
2  Electronics_Imports  8.157330
3     Urban_Population  6.792266